#include "cards.h"
#include "card_ids.h"


#define POKEMON_CARD(uuid, name_id, set, set_id, rarity, ...) \
	{.header = {uuid, CardType::CARD_POKEMON, name_id, set, set_id, rarity}, .pokemon = {__VA_ARGS__}}

#define TRAINER_CARD(uuid, name_id, set, set_id, rarity, subtype, effect_id) \
	{.header = {uuid, CardType::CARD_TRAINER, name_id, set, set_id, rarity}, .trainer = {subtype, effect_id}}

#define ENERGY_CARD(uuid, name_id, set, set_id, rarity, ...) \
	{.header = {uuid, CardType::CARD_ENERGY, name_id, set, set_id, rarity}, .energy = {__VA_ARGS__}}

const Card cards[] = {
	POKEMON_CARD(UUID::NONE, 0, Set::NONE, 0, Rarity::NONE, 0, 0, Type::NONE, Type::NONE, 0, Type::NONE, Type::NONE, 0, 0, 0, 0),
	// Base Set
	POKEMON_CARD(UUID::BASE_SET_ALAKAZAM, 0, Set::SET_BASE_SET, 1, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_PSYCHIC, Type::NONE, 80, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_BLASTOISE, 0, Set::SET_BASE_SET, 2, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_WATER, Type::NONE, 100, Type::TYPE_LIGHTNING, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CHANSEY, 0, Set::SET_BASE_SET, 3, Rarity::RARITY_HOLO, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 120, Type::TYPE_FIGHTING, Type::TYPE_PSYCHIC, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CHARIZARD, 0, Set::SET_BASE_SET, 4, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_FIRE, Type::NONE, 120, Type::TYPE_WATER, Type::TYPE_FIGHTING, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CLEFAIRY, 0, Set::SET_BASE_SET, 5, Rarity::RARITY_HOLO, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 40, Type::TYPE_FIGHTING, Type::TYPE_PSYCHIC, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_GYARADOS, 0, Set::SET_BASE_SET, 6, Rarity::RARITY_HOLO, 2, 0, Type::TYPE_WATER, Type::NONE, 100, Type::TYPE_GRASS, Type::TYPE_FIGHTING, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_HITMONCHAN, 0, Set::SET_BASE_SET, 7, Rarity::RARITY_HOLO, 1, 0, Type::TYPE_FIGHTING, Type::NONE, 70, Type::TYPE_PSYCHIC, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MACHAMP, 0, Set::SET_BASE_SET, 8, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_FIGHTING, Type::NONE, 100, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MAGNETON, 0, Set::SET_BASE_SET, 9, Rarity::RARITY_HOLO, 2, 0, Type::TYPE_LIGHTNING, Type::NONE, 60, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MEWTWO, 0, Set::SET_BASE_SET, 10, Rarity::RARITY_HOLO, 1, 0, Type::TYPE_PSYCHIC, Type::NONE, 60, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0,),
	POKEMON_CARD(UUID::BASE_SET_NIDOKING, 0, Set::SET_BASE_SET, 11, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_GRASS, Type::NONE, 90, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_NINETALES, 0, Set::SET_BASE_SET, 12, Rarity::RARITY_HOLO, 2, 0, Type::TYPE_FIRE, Type::NONE, 80, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_POLIWRATH, 0, Set::SET_BASE_SET, 13, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_WATER, Type::NONE, 90, Type::TYPE_GRASS, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_RAICHU, 0, Set::SET_BASE_SET, 14, Rarity::RARITY_HOLO, 2, 0, Type::TYPE_LIGHTNING, Type::NONE, 80, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_VENUSAUR, 0, Set::SET_BASE_SET, 15, Rarity::RARITY_HOLO, 3, 0, Type::TYPE_GRASS, Type::NONE, 100, Type::TYPE_FIRE, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ZAPDOS, 0, Set::SET_BASE_SET, 16, Rarity::RARITY_HOLO, 1, 0, Type::TYPE_LIGHTNING, Type::NONE, 90, Type::NONE, Type::TYPE_FIGHTING, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_BEEDRILL, 0, Set::SET_BASE_SET, 17, Rarity::RARITY_RARE, 3, 0, Type::TYPE_GRASS, Type::NONE, 80, Type::TYPE_FIRE, Type::TYPE_FIGHTING, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DRAGONAIR, 0, Set::SET_BASE_SET, 18, Rarity::RARITY_RARE, 2, 0, Type::TYPE_COLORLESS, Type::NONE, 80, Type::NONE, Type::TYPE_PSYCHIC, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DUGTRIO, 0, Set::SET_BASE_SET, 19, Rarity::RARITY_RARE, 2, 0, Type::TYPE_FIGHTING, Type::NONE, 70, Type::TYPE_GRASS, Type::TYPE_LIGHTNING, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ELECTABUZZ, 0, Set::SET_BASE_SET, 20, Rarity::RARITY_RARE, 1, 0, Type::TYPE_LIGHTNING, Type::NONE, 70, Type::TYPE_FIGHTING, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ELECTRODE, 0, Set::SET_BASE_SET, 21, Rarity::RARITY_RARE, 2, 0, Type::TYPE_LIGHTNING, Type::NONE, 80, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_PIDGEOTTO, 0, Set::SET_BASE_SET, 22, Rarity::RARITY_RARE, 2, 0, Type::TYPE_COLORLESS, Type::NONE, 60, Type::TYPE_LIGHTNING, Type::TYPE_FIGHTING, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ARCANINE, 0, Set::SET_BASE_SET, 23, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_FIRE, Type::NONE, 100, Type::TYPE_WATER, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CHARMELEON, 0, Set::SET_BASE_SET, 24, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_FIRE, Type::NONE, 80, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DEWGONG, 0, Set::SET_BASE_SET, 25, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_WATER, Type::NONE, 80, Type::TYPE_LIGHTNING, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DRATINI, 0, Set::SET_BASE_SET, 26, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 40, Type::NONE, Type::TYPE_PSYCHIC, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_FARFETCH_D, 0, Set::SET_BASE_SET, 27, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 50, Type::TYPE_LIGHTNING, Type::TYPE_FIGHTING, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_GROWLITHE, 0, Set::SET_BASE_SET, 28, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_FIRE, Type::NONE, 60, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_HAUNTER, 0, Set::SET_BASE_SET, 29, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_PSYCHIC, Type::NONE, 60, Type::NONE, Type::TYPE_FIGHTING, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_IVYSAUR, 0, Set::SET_BASE_SET, 30, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_GRASS, Type::NONE, 60, Type::TYPE_FIRE, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_JYNX, 0, Set::SET_BASE_SET, 31, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_PSYCHIC, Type::NONE, 70, Type::TYPE_PSYCHIC, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_KADABRA, 0, Set::SET_BASE_SET, 32, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_PSYCHIC, Type::NONE, 60, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_KAKUNA, 0, Set::SET_BASE_SET, 33, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_GRASS, Type::NONE, 80, Type::TYPE_FIRE, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MACHOKE, 0, Set::SET_BASE_SET, 34, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_FIGHTING, Type::NONE, 80, Type::TYPE_PSYCHIC, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MAGIKARP, 0, Set::SET_BASE_SET, 35, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_WATER, Type::NONE, 30, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MAGMAR, 0, Set::SET_BASE_SET, 36, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_FIRE, Type::NONE, 50, Type::TYPE_WATER, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_NIDORINO, 0, Set::SET_BASE_SET, 37, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_GRASS, Type::NONE, 60, Type::TYPE_PSYCHIC, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_POLIWHIRL, 0, Set::SET_BASE_SET, 38, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_WATER, Type::NONE, 60, Type::TYPE_GRASS, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_PORYGON, 0, Set::SET_BASE_SET, 39, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 30, Type::TYPE_FIGHTING, Type::TYPE_PSYCHIC, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_RATICATE, 0, Set::SET_BASE_SET, 40, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_COLORLESS, Type::NONE, 60, Type::TYPE_FIGHTING, Type::TYPE_PSYCHIC, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_SEEL, 0, Set::SET_BASE_SET, 41, Rarity::RARITY_UNCOMMON, 1, 0, Type::TYPE_WATER, Type::NONE, 60, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_WARTORTLE, 0, Set::SET_BASE_SET, 42, Rarity::RARITY_UNCOMMON, 2, 0, Type::TYPE_WATER, Type::NONE, 70, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ABRA, 0, Set::SET_BASE_SET, 43, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_PSYCHIC, Type::NONE, 30, Type::TYPE_PSYCHIC, Type::NONE, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_BULBASAUR, 0, Set::SET_BASE_SET, 44, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 40, Type::TYPE_FIRE, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CATERPIE, 0, Set::SET_BASE_SET, 45, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 40, Type::TYPE_FIRE, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_CHARMANDER, 0, Set::SET_BASE_SET, 46, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIRE, Type::NONE, 50, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DIGLETT, 0, Set::SET_BASE_SET, 47, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIGHTING, Type::NONE, 30, Type::TYPE_GRASS, Type::TYPE_LIGHTNING, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DODUO, 0, Set::SET_BASE_SET, 48, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 50, Type::TYPE_LIGHTNING, Type::TYPE_FIGHTING, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_DROWZEE, 0, Set::SET_BASE_SET, 49, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_PSYCHIC, Type::NONE, 50, Type::TYPE_PSYCHIC, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_GASTLY, 0, Set::SET_BASE_SET, 50, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_PSYCHIC, Type::NONE, 30, Type::NONE, Type::TYPE_FIGHTING, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_KOFFING, 0, Set::SET_BASE_SET, 51, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 50, Type::TYPE_PSYCHIC, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MACHOP, 0, Set::SET_BASE_SET, 52, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIGHTING, Type::NONE, 50, Type::TYPE_PSYCHIC, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_MAGNEMITE, 0, Set::SET_BASE_SET, 53, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_LIGHTNING, Type::NONE, 40, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_METAPOD, 0, Set::SET_BASE_SET, 54, Rarity::RARITY_COMMON, 2, 0, Type::TYPE_GRASS, Type::NONE, 70, Type::TYPE_FIRE, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_NIDORAN_M, 0, Set::SET_BASE_SET, 55, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 40, Type::TYPE_PSYCHIC, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_ONIX, 0, Set::SET_BASE_SET, 56, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIGHTING, Type::NONE, 90, Type::TYPE_GRASS, Type::NONE, 3, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_PIDGEY, 0, Set::SET_BASE_SET, 57, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 40, Type::TYPE_LIGHTNING, Type::TYPE_FIGHTING, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_PIKACHU, 0, Set::SET_BASE_SET, 58, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_LIGHTNING, Type::NONE, 40, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_POLIWAG, 0, Set::SET_BASE_SET, 59, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_WATER, Type::NONE, 40, Type::TYPE_GRASS, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_PONYTA, 0, Set::SET_BASE_SET, 60, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIRE, Type::NONE, 40, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_RATTATA, 0, Set::SET_BASE_SET, 61, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_COLORLESS, Type::NONE, 30, Type::TYPE_FIGHTING, Type::TYPE_PSYCHIC, 0, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_SANDSHREW, 0, Set::SET_BASE_SET, 62, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIGHTING, Type::NONE, 40, Type::TYPE_GRASS, Type::TYPE_LIGHTNING, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_SQUIRTLE, 0, Set::SET_BASE_SET, 63, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_WATER, Type::NONE, 40, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_STARMIE, 0, Set::SET_BASE_SET, 64, Rarity::RARITY_COMMON, 2, 0, Type::TYPE_WATER, Type::NONE, 60, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_STARYU, 0, Set::SET_BASE_SET, 65, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_WATER, Type::NONE, 40, Type::TYPE_LIGHTNING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_TANGELA, 0, Set::SET_BASE_SET, 66, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 50, Type::TYPE_FIRE, Type::NONE, 2, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_VOLTORB, 0, Set::SET_BASE_SET, 67, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_LIGHTNING, Type::NONE, 40, Type::TYPE_FIGHTING, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_VULPIX, 0, Set::SET_BASE_SET, 68, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_FIRE, Type::NONE, 50, Type::TYPE_WATER, Type::NONE, 1, 0, 0, 0),
	POKEMON_CARD(UUID::BASE_SET_WEEDLE, 0, Set::SET_BASE_SET, 69, Rarity::RARITY_COMMON, 1, 0, Type::TYPE_GRASS, Type::NONE, 40, Type::TYPE_FIRE, Type::NONE, 1, 0, 0, 0),
};

const uint16_t CARD_DATABASE_SIZE = sizeof(cards) / sizeof(Card);

const Card* get_card_by_id(uint16_t id) {
	if(id >= CARD_DATABASE_SIZE) {
		return nullptr;
	}
	
	return &cards[id];
}